### ISSUE TITLE
Kill.Killer may be nil

### ISSUE THREAD

**Issue by Linus4** [markus-wa/demoinfocs-golang#156]
**Describe the bug**
The Killer pointer in the events.Kill type may be nil. In my case, the player fell to his death.
Similar to #151 .

**To Reproduce**
[Link to demo](https://user.informatik.uni-goettingen.de/~linus.weber/s11_severity_de_inferno.dem)

Code:
[Line in parser code](https://github.com/markus-wa/demoinfocs-golang/blob/d7347829b857e430b495788927511915076081ea/game_events.go#L279)

```go
type Kill struct {
	KillerName string
	KillerTeam common.Team
	VictimName string
	VictimTeam common.Team
	Weapon     string
}

parser.RegisterEventHandler(func(e event.Kill) {	
	kill := ocom.Kill{
		KillerName: e.Killer.Name,
		KillerTeam: e.Killer.Team,
		VictimName: e.Victim.Name,
		VictimTeam: e.Victim.Team,
		Weapon:     e.Weapon.Weapon.String(),
}
```

**Expected behavior**
`Kill.Killer` should be the same as `Kill.Victim`. Also, the `Kill.Weapon` could be something like suicide or falling instead of `UNKNOWN`. Maybe don't dispatch a Kill event at all or add a comment in the documentation.

**Library version**
v1.3.3

**Comment by Linus4** [comment]
I just discovered that the Victim pointer in the Kill type may also be nil. It occurred when a player left the server, presumably due to his game crashing.

**Comment by markus-wa** [comment]
Hey @Linus4 

`Killer` being `nil` is intended. IIRC the issue is that we cannot differentiate between different kinds of `UNKNOWN`. It could be self damage from a molotov, falling or the `kill` command.

I will update the docs accordingly.

> I just discovered that the Victim pointer in the Kill type may also be nil. It occurred when a player left the server, presumably due to his game crashing.

Interesting, I will try to look into this.

**Comment by Linus4** [comment]
I also just found that the Shooter from the WeaponFire event may be nil. All shot from one player had the nil pointer until he reconnected to the server.

**Comment by markus-wa** [comment]
I looked into `Kill.Killer` a bit more and noticed that in this case for the demo you linked we should have returned `EqWorld` as weapon since the event has the `weapon` attribute as `weapon_worldspawn`.

In addition I'm adding the comment `May be nil for world damage (EqWorld)` to `Kill.Killer`

> I also just found that the Shooter from the WeaponFire event may be nil. All shots from one player had the nil pointer until he reconnected to the server.

I could not reproduce this with any demo from a set of 27 (including the one you linked).
Can you link me the demo where you found this? Ideally with the exact tick number, but the demo alone is also good enough 🙂.

Thanks!

**Comment by Linus4** [comment]
These are the ticks where a weapon is fired, but Shooter is nil (all during warmup):
```
467
480
497
510
523
536
611
614
617
620
623
626
638
661
664
667
670
673
675
679
732
756
771
791
856
871
874
877
880
883
886
889
892
947
950
954
956
997
1000
1003
1173
1198
1212
1225
1238
1251
1323
1326
1327
1329
1332
1335
1338
1340
1341
1344
1347
1349
1353
1353
1355
```

[Link to demo](https://user.informatik.uni-goettingen.de/~linus.weber/ueg_5_kitsc_map1de_inferno.dem)

Thank you for looking into it! :)

**Comment by markus-wa** [comment]
Cheers! will look into it tonight

**Comment by markus-wa** [comment]
So I debugged a bit and looked at the demo in GOTV and I think unfortunately we can't fix the `WeaponFire` issue.

Here is one of the `WeaponFire` events in question (by `xæct`):
```
weapon_fire: Tick=1848 UserID=12 Weapon=Knife

Players by UserID:
2 GOTV
4 srebbiT
5 marcelo2k
6 DWecken2k
7 CowHitFace
8 GotchYa
10 ¿ncapu
13 sw1tch2k ♥️ KLBE
14 Duplo
15 Linuz
16 xæct
```

Some ticks later we get a `Kill` event from the same player (`xæct`) killing `sw1tch2k`.
```
~2470 player_death: Tick=1848 AttackerID=12 Weapon=M4A4

Players by UserID:
2 GOTV
4 srebbiT
5 marcelo2k
6 DWecken2k
7 CowHitFace
8 GotchYa
10 ¿ncapu
13 sw1tch2k ♥️ KLBE
14 Duplo
15 Linuz
16 xæct
```

Now if we look at this in GOTV, this is how it looks like:
![image](https://user-images.githubusercontent.com/5138316/68608748-eb350900-04b3-11ea-9562-1a54d0f91e36.png)

Notice how in the killfeed it looks like a suicide by `sw1tch2k`

So since GOTV can't even handle it itself, I think we're out of luck 🙁

**Comment by Linus4** [comment]
I see, you're right. A comment in the WeaponFire type is everything we can do then.

I did some work in Haskell before where you always have to handle the possibility of a field being `nil`. There is a type `Maybe`: e.g. `Maybe Int` with `Just 3` or `Nothing`. You have to write your function so that they always handle both cases. I guess you should always check pointers in golang if they are `nil` before you use them.. :D

**Comment by markus-wa** [comment]
Yeah it's unfortunate that Go doesn't have this. I personally love using Kotlin for that reason, no more NPE, nil pointer dereference etc.

Oh well, it is how it is 🙂
