### ISSUE TITLE
Issues with how prop values are currently handled

### ISSUE THREAD

**Issue by zyphie** [markus-wa/demoinfocs-golang#24]
Currently, there are limitations on how one can use prop values.

**1. Ability to get current prop value**

Currently we can only get prop value on updates. One can solve this by storing the value in a local variable, but this should perhaps be stored on the entity.

Even if we store the value locally, we face an issue: Let's say we want to store prop values when a FireEntityCreatedEvent happens. FirePropertyUpdate has not been fired yet, so we cannot store this data.

**2. Multiple values fired at same tick if value differing for default(?) value on FirePropertyUpdate after a FireEntityCreatedEvent**

E.g. "m_iTeamNum" on "CBaseCSGrenadeProjectile" seems to default to 3, so if the value actually is 3, FirePropertyUpdate fires once with this value. If this value is actually 2, FirePropertyUpdate is fired twice on the same tick (first with value 3, then 2).

Broad overview of what I think needs to be done for 1.:
- Specify props one want stored on a type of entity
- On FirePropertyUpdate for these props, store the data to Entity
- Have a handler on the entity that is fired when the data is populated (e.g. at end of tick, as we then should get the latest, valid value from FirePropertyUpdate re: 2.)

**Comment by markus-wa** [comment]
Is 2. different from #25?

If not I think we can close this with #26 being merged?

**Comment by zyphie** [comment]
It's different. #25 is about outputting wrong values. 

This issue is an issue of outputting multiple values on the same tick (when, seemingly, the value differs from a default value). This only happens when a prop value is initialized on an entity. 

Currently, one can amend this by, when a prop update is fired, we wait for e.g. the TickEnd event, and then collect the prop value. However, it would be nice if this wasn't necessary, although I'm not sure if it is possible.

**Comment by markus-wa** [comment]
I think we can't get around doing it the way we do now. The reason for this is that we don't know in advance whether or not a `PropertyEntry`'s value is gonna be the default value.

Here's what is done:
1. Apply baseline on entity, this fires the update with the default value
2. Apply entity-specific update, this may or may not fire new values

So what could be done would be to only register the update handler after the baseline has been applied (if we fired the `EntityCreatedEvent` after the baseline has been applied). But then you'd have to manually read the default value in some cases and let it be set by the update-handler in others. This would mean you have to write something like:

```go
prop := playerEntity.FindProperty("m_iTeamNum")
pl.Team = common.Team(val.IntVal)

prop.RegisterPropertyUpdateHandler(func(val st.PropValue) {
	pl.Team = common.Team(val.IntVal)
})
```

instead of just

```go
playerEntity.FindProperty("m_iTeamNum").RegisterPropertyUpdateHandler(func(val st.PropValue) {
	pl.Team = common.Team(val.IntVal)
})
```

I don't think this is a good solution.

The only other way I see would be to let the parser wait until a tick has ended and then fire all pending updates there but that would require a lot of additional code and isn't an option in my eyes either since it's very hacky.

Any thoughts?

**Comment by markus-wa** [comment]
Oh and could you give me an example of what you were trying to do when you encountered this?

**Comment by zyphie** [comment]
Yeah, I think you are right. If there isn't an actual solution to the problem, I think any fix is probably best left to be done outside the library. 

I will probably do something like: RegisterPropertyUpdateHandler on a prop -> on updates, create a  RegisterEventHandler on TickDoneEvent -> get the prop value when TickDoneEvent fires -> unregister handler on TickDoneEvent.

When I encountered this, I was trying to get the index of the model of CSBaseGrenadeProjectile to determine if it is a flash or HE.

**Comment by markus-wa** [comment]
Actually, I think I found a way to get rid of the baseline update now.

1. Apply baseline
2. Apply entity-specific update
3. Fire EntityCreatedEvent
4. Fire updates on all properties

I'm just working on putting it all together but I think this will do the trick!

**Comment by markus-wa** [comment]
Changed on dev, hope this helps

**Comment by zyphie** [comment]
It seems to fire once now, regardless of whether it is the baseline value or not. Great stuff!

**Comment by markus-wa** [comment]
👍
