### ISSUE TITLE
Have you figured out how to extract the voice chat from demos?

### ISSUE THREAD

**Issue by EloB** [markus-wa/demoinfocs-golang#243]
A would like to extract the voice from the demo. Have you managed todo that?

**Comment by markus-wa** [comment]
Most demos don't contain voice chat data so I haven't looked into it.

I see you've also asked in https://github.com/saul/demofile/issues/83 - maybe it could be done with https://github.com/hraban/opus, but I'm not sure.

**Comment by EloB** [comment]
@markus-wa Thanks for your response... Would be amazing if it was possible :)

**Comment by markus-wa** [comment]
do you have an example demo with voice chat by chance? not sure I'll find time to look into it any time soon to be honest but if so I'd at least need some test data.

**Comment by EloB** [comment]
@markus-wa I will love you long time if you manage to do it xD <3 https://easyupload.io/tgcpaw

**Comment by Julien2313** [comment]
I'm pretty sure you don't have voices for demos from valve, but you have them in faceit (not sure for ESEA)

**Comment by markus-wa** [comment]
Yup correct @Julien2313 - the linked demo is from esportal, so they might support that (haven't had time to look at the demo though)

**Comment by EloB** [comment]
I'm sure that voice is included in that demo. I've also managed to mute specific players in the demo by console commands (mute button on scoreboard doesn't work but commands works) so each voice is separate recorded and included in the demo.

**Comment by EloB** [comment]
I don't remember if it was:
`voice_show_mute`, `voice_mute [Player #]`, `voice_unmute [Player #]` commands or if it was something with volume of a specific player but I'm sure that I got it to work.

**Comment by EloB** [comment]
I think it was this command that worked:
`voice_player_volume [playerid] [volume]`

Set `volume` to `0`.

Use `voice_show_mute` to see players id.

**Comment by ericek111** [comment]
Extracting voice is relatively easy. PITA is converting the voice data from CELT codec to raw audio. Here's some dirty code from my experimental Java demo parser: https://github.com/ericek111/GODemolyser/blob/master/GODemolyser/src/eu/lixko/godemolyser/Main.java#L91

Basically you just stitch together the byte arrays from CSVCMsg_VoiceData messages that belong to your player of interest. The voice chat is CELT-encoded with a frame size of 512 B, output audio is 22050 Hz.

I found that the best way to call the codec is to use freely available header files and use them to link against CS:GO's binaries. That's because pure CELT decodes only gibberish. They use something like 0.8.0 or 0.7.0 in CS:GO, though I've had no luck with these versions standalone. Headers from 0.11.0 work fine: https://github.com/mumble-voip/celt-0.11.0

Here's a gist of my program. I use it frequently to extract voice chat of a player from several demos, to stitch it together and encode to FLAC (though that part is automated from a PHP script): https://gist.github.com/ericek111/abe5829f6e52e4b25b3b97a0efd0b22b

**Comment by markus-wa** [comment]
thanks @ericek111 for the detailed instructions - I'll give it a go when I find some time :slightly_smiling_face:

**Comment by markus-wa** [comment]
I have one question though:

> They use something like 0.8.0 or 0.7.0 in CS:GO

How do we know this if 0.11.0 seems to work for decoding?

**Comment by ericek111** [comment]
I don't remember, sorry, last I looked into this was two years ago. They don't strip symbols from `audio_celt_client.so`. The headers are a convenient way to access those functions and structures.

CS:GO is basically open-source now (lol), so there's no need to reverse-engineer everything: https://github.com/perilouswithadollarsign/cstrike15_src/blob/29e4c1fda9698d5cebcdaf1a0de4b829fa149bf8/engine/voice_codecs/celt/voiceencoder_celt.cpp

**Comment by markus-wa** [comment]
huh, surprised that is not getting a DMCA notice. but thanks for the link, good to know.

**Comment by ubbs** [comment]
Hello, guys I have the same problem. But couldn't find a solution yet. I need the voice chat (CT side) on the 9th round? Is there any way to extract it. Its my own voice. I don't know anything about coding btw...

**Comment by markus-wa** [comment]
Hi @ubbs - if you're unfamiliar with coding and just need it as a one-off I'd suggest using some kind of audio recording software (e.g. Audacity) and then opening the demo in CS:GO to listen to it.

**Comment by markus-wa** [comment]
Hi all

There is now a working example here: https://github.com/saiko-tech/csgo-demo-voice-capture-example
