### ISSUE TITLE
runtime error when registering events of a demo file

### ISSUE THREAD

**Issue by pbuzulan** [markus-wa/demoinfocs-golang#258]
**Describe the bug**
After analyzing a few demos I end every time fighting the same error. 
`panic: runtime error: invalid memory address or nil pointer dereference`

**To Reproduce**
Demo link: https://www.hltv.org/download/demo/61643 (first map - inferno)
In particular, you will see after round 12 (score=8:4) the following attributes of Killerplayer does not work at all.
PLEASE NOTE: ALL OF THESE ARE NOT WORKING!

Code:
```go
p.RegisterEventHandler(func(k events.Kill) {
	killerPositionX, killerPositionY := mapMetadata.TranslateScale(k.Killer.Position().X, k.Killer.Position().Y)
	k.Killer.TeamState.Members()
	int(k.Killer.SteamID64)
	k.Killer.Name
	k.Killer.IsBlinded()
	k.Killer.IsPlanting
	k.Killer.IsDefusing
	k.Killer.IsReloading
	k.Killer.Weapons()
	k.Killer.HasDefuseKit()
        k.Killer.HasHelmet()
	}
```

**Expected behavior**
I expect to get out the needed information reported before.

**Library version**
e.g. v2.5.0

**Additional context**
Same information if asked for the Victim works. I cannot understand why (in this particular demo file).
Yesterday I was analyzing another demo from another tournament and the same error came out (I do not have the error anymore, unfortunately).
This might be referred somehow to [#162](https://github.com/markus-wa/demoinfocs-golang/issues/162) issue already closed.

**Comment by markus-wa** [comment]
Hi @pbuzulan - the docs for `events.Kill.Killer` mention that "May be nil for world damage (EqWorld) or if the demo is partially corrupt (player is 'unconnected', see #156 and #172)." have you checked the docs and verified if this is not because of "world damage"?

#156 and #172 are also related, if this is like #172 there might be nothing we can do.

can you post a screenshot of this kill from CS:GO's demo viewer? especially the kill feed for the affected events.

thanks!

**Comment by markus-wa** [comment]
Closing this, feel free to re-open with more details if you think there is more to investigate
