### ISSUE TITLE
Player.Spotters() is not "Line of Sight" / FOV

### ISSUE THREAD

**Issue by xavier-rodet** [markus-wa/demoinfocs-golang#262]
Hey @markus-wa it's been a while since I have been active on this repo, which btw seems to be better and better 🙂 

I have noticed that the spotters features added in #121 is not exactly what was asked in #114 (players in POV).

Spotters are the players who spots the enemies for the whole team, which means that if : 
T1 sees CT1 and then T2 joins them in the fight and also sees CT1, the only spotter of CT1 will be T1 (T2 will never trigger the event).

So relying on spotters for POV detection is only fine for duels (1v1) but won't works as expected for every players in teamfights (XvX).

This can be verified on any demo involving team fights where there is a small delay between 2 players of the same team seeing  the same enemy on their POV.

I'm not even sure this is something possible to do directly from the demo file, but could you take a look to add a new feature about players detection directly from POV? 

Thanks!

**Comment by markus-wa** [comment]
Hey @xavier-rodet

You're right, Spotters doesn't relate to POVs. I was actually aware of this at the time of implementation, but I wasn't aware of the limitation on multiple players.
But yeah Spotters may also trigger with players outside the POV or may not trigger for players inside the POV, even if it's a "1v1".

This should probably be made clearer in the docs.

Spotters basically just represents what's happening on the radar view, rather than any player's POV.

Unfortunately I don't think there's a way to do POV detection without having a 3D representation of the map running (e.g. by running the game engine in some form or reading the map file). So this feature would be outside the scope of this library.

**Comment by xavier-rodet** [comment]
Yeah I meant FOV 👍 

Thank you for confirming what I was thinking, this is out of this project indeed & using the map file was also what I had in mind to solve this!

**Comment by markus-wa** [comment]
you probably already know how to go about it, but just in case, this might be interesting: https://www.youtube.com/watch?v=sv79Mgt_FmY

**Comment by xavier-rodet** [comment]
Wow thank you it's gonna be really usefull to me 👍

**Comment by markus-wa** [comment]
Updated the docs :slightly_smiling_face:
