### ISSUE TITLE
Apparently property 'm_iHealth' can be… missing?

### ISSUE THREAD

**Issue by sirherrbatka** [markus-wa/demoinfocs-golang#458]
**Describe the bug**
I am not sure if this is bugged demo or what but this demo seems to indicate that there can be some sort of corner case during data tables parsing not covered.

**To Reproduce**
Check this demo file: https://antiochia.duckdns.org/index.php/s/zqf5KTq8PcmCFj9

**Expected behavior**
Not crash. 

**Library version**
beta.5

**Comment by saul** [comment]
How old is this demo? It has a protocol version of 13942, whereas newer demos have 13964.

**Comment by sirherrbatka** [comment]
It is on the older side, perhaps 2 weeks (at most) after CS2 went live.

**Comment by markus-wa** [comment]
I guess it's fair to say we can just return 0 if the prop is missing :crossed_fingers:

**Comment by akiver** [comment]
This demo comes from Faceit during the CS2 limited test phase.
The player prop `m_hPlayerPawn` doesn't point to a `CCSPlayerPawn` instance as it should but rather to a `CBaseModelEntity`.
That's why it crashes.

I did a test on this [branch](https://github.com/markus-wa/demoinfocs-golang/commit/dff72bcb36b0b6556a996eb4bd65dd13bf30525a), and even if we prevent the panic, we must patch all player's functions that rely on the pawn entity otherwise calling them would lead to a panic.

**Comment by markus-wa** [comment]
Might not be worth it then to only support such a limited set of demos.

If anyone finds a nice fix I'd be happy to incorporate, but otherwise this might end up as a `wontfix`

**Comment by jhaikonen** [comment]
I ran to the same issue with demo from esportal where the round has been resetted or something like that, and got the same error 'm_iHealth' missing. 

Ran the same demo with the branch mentioned by akiver (test-458) and it did not crash, but esportal demos don't have kill events etc unless you use the branch s2-fake-CMsgSource1LegacyGameEventList.

Anyway; I guess this is something to look into anyways and not just 'wontfix' 🤔

**Comment by jhaikonen** [comment]
Update: merged test-458 to s2-fake-CMsgSource1LegacyGameEventList locally and was able to parse the demo ^^

**Comment by markus-wa** [comment]
fixed in latest release - thanks @akiver
