### ISSUE TITLE
EOF: demo stream ended unexpectedly (ErrUnexpectedEndOfDemo)

### ISSUE THREAD

**Issue by moxbo** [markus-wa/demoinfocs-golang#463]
**Describe the bug**
Parsing the demo runs into an error
{"time":"2023-10-31T14:32:47.2647617+01:00","level":"FATAL","prefix":"-","file":"main_dev.go","line":"157","message":"failed to parse demo: unexpected EOF: demo stream ended unexpectedly (ErrUnexpectedEndOfDemo)"}

**To Reproduce**
Any demo of "https://www.hltv.org/matches/2367699/jano-vs-metizport-yalla-compass-fall-2023-contenders" cannot be parsed
```go
f, err := os.Open("jano-vs-metizport-m3-mirage.dem")
					if err != nil {
						log.Fatal(err)
					}
					defer f.Close()

					info, err := cs.ParseDemo(f)
					if err != nil {
						log.Fatal(err)
					}
```

Code:
```go
func ParseDemo(r io.Reader) (result *DemoInfoCs2, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = errors.Errorf("panic occurred: %v", r)
			result = nil
		}
	}()

	//var demoParsingStarted bool
	var demo DemoInfoCs2
	p := demoinfocs.NewParser(r)
	defer p.Close()

	if err := p.ParseToEnd(); err != nil {
		return nil, errors.Wrap(err, "failed to parse demo")
	}

	return &demo, nil
}
```

**Expected behavior**

**Library version**
e.g. v4.0.0-beta.5

**Comment by markus-wa** [comment]
`ErrUnexpectedEndOfDemo` is not a fatal error, it is similar to `io.EOF` and just signals that the demo is incomplete because the server didn't properly flush the demo to disk (see documentation on `ErrUnexpectedEndOfDemo`).

as you can see below the demos are being parsed correctly.
```
 go run ./examples/print-events/print_events.go -demo ~/Downloads/jano-vs-metizport-m1-overpass.dem
```

![image](https://github.com/markus-wa/demoinfocs-golang/assets/5138316/689181d8-200d-4d55-ad16-f277dfcc5c7e)
