### ISSUE TITLE
examples/print-events: nil pointer dereference for certain demos

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#69]
**Describe the bug**
Memory error for parsing demo file

**To Reproduce**
https://www.hltv.org/download/demo/46633
Related demo file is the demo file of overpass map.

**Expected behavior**
Succesful parsing.

**Library version**
v1.0.0-beta.0

**Additional context**
Screnshot:
https://ibb.co/LQSbxH5

**Comment by markus-wa** [comment]
Thanks for the report.

This seems to be an issue with the example code, not the library itself.
I have corrected it accordingly (1b48fe238c480f5ab7b12a4339053183764139d3).

Can you try it with the latest version from master and verify that it works for you?

**Comment by markus-wa** [comment]
Running the example as `go run -tags debugdemoinfocs examples/print-events/print_events.go -demo path/to/replay.dem` gives the following output around the event in question:

```
GameEvent: player_disconnect Data: map[name:iBmatty123 networkid:STEAM_1:1:14092031 userid:30 reason:Disconnect]
GameEvent: item_remove Data: map[userid:30 item:defuser defindex:0]
GameEvent: item_remove Data: map[item:m4a1 defindex:16 userid:30]
GameEvent: item_remove Data: map[userid:30 item:vesthelm defindex:0]
GameEvent: item_remove Data: map[item:knife defindex:509 userid:30]
GameEvent: item_remove Data: map[userid:30 item:hkp2000 defindex:61]
GameEvent: player_death Data: map[revenge:0 noreplay:true weapon_originalowner_xuid: penetrated:0 userid:30 weapon_itemid: weapon_fauxitemid: dominated:0 attacker:30 assister:0 headshot:false weapon:world]
? <World> ?
GameEvent: player_team Data: map[autoteam:false silent:false isbot:false userid:30 team:0 oldteam:3 disconnect:true]
```

Notice that there's a `player_disconnect` event before `player_death` (along with `player_team`, a team swap and `item_remove`, the players weapons being dropped).

This doesn't make much sense in my eyes and it's not the default behavior of most CS servers.
Usually there are no events related to a player after he disconnects.
(I suspect this was caused by a custom plugin running on the server like [eBot](https://github.com/deStrO/eBot-CSGO)).

After `player_disconnect` the player is removed from the parser's player list, so the parser doesn't know the victim's / attacker's user-id (30).


As a conclusion I believe the current behaviour is maybe not ideal but I don't see a clean way to improve it without breaking other things. Suggestions are welcome but seeing how it's an edge case and the events in question are outside of the normal game time, I think changes to address this should be minimal (if there are even any).

**Comment by quancore** [comment]
First of all, thanks for your good investigation. I do not know whether there is a handling mechanism for disconnected players. Maybe the events related to a disconnected player can be ignored?

**Comment by markus-wa** [comment]
The disconnect mechanism is here: https://github.com/markus-wa/demoinfocs-golang/blob/master/game_events.go#L235

In this case I think it would be correct to discard the events, but I'm not sure how to do a check that makes sure the event is useless. 
For example: if the parser failed to read a connected player due to a bug and we just check `if victim == nil` we will suppress all events of that player and hide the true underlying issue.

- It also needs to be considered what should be done if only the killer is unknown but the victim is known or the other way around (you never know what happens with all these strange demos).

If we want to be sure the event can be ignored we would need to track disconnected players - at which point we could also just _not_ ignore it and fill the players correctly.
I'd be open to accepting this change, it could probably be done with a new field `GameState.allPlayersByUserID` (or some other name) that is identical to [`GameState.playersByUserID`](https://github.com/markus-wa/demoinfocs-golang/blob/master/game_state.go#L16) except for the disconnect mechanism

Would you be interested in creating a PR?

**Comment by quancore** [comment]
As far as I understand, there should be a connection status variable in the player struct and it should be adjusted according to connection/disconnection events. Therefore, If a player had a connected status but now he is disconnected (it can be checked existence - nonexistent as well), we are pretty sure that he is truly disconnected and we can discard any falsely coded events related to this player (victim, killer or any other). If there is a player who parser never read correctly I think it is not a consideration for the parser.
I am unable to add this addition because I am a beginner in go but it would be perfect to add it.

**Comment by markus-wa** [comment]
> As far as I understand, there should be a connection status variable in the player struct and it should be adjusted according to connection/disconnection events. Therefore, If a player had a connected status but now he is disconnected (it can be checked existence - nonexistent as well), we are pretty sure that he is truly disconnected and we can discard any falsely coded events related to this player (victim, killer or any other). 

Yeah your suggestion should work I think (except that re-connected players would have a new user-ID, so we can only update on disconnect, not re-connect, but that shouldn't matter in this case).

> If there is a player who parser never read correctly I think it is not a consideration for the parser.

I disagree, this can lead to confusing and hard to track down bugs IMO.

> I am unable to add this addition because I am a beginner in go but it would be perfect to add it.

Ok, that's fine 🙂. It will probably be a while before I find time to do this though. If you change your mind I'd  more than happy to help out and review any changes.
