### ISSUE TITLE
Inconsistent scoreUpdated event

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#84]
**Describe the bug**
When scoreUpdated event is called, it can return wrong updates like:
https://ibb.co/3dWhpFj

**To Reproduce**
https://www.hltv.org/download/demo/46633

**Expected behavior**
scoreUpdates sholud be consistent.If eventually consistent, there should be indication that update is invalid.

**Library version**
e.g. v1.x.x

**Additional context**
Add any other context about the problem here - like your OS if that could be relevant.

**Comment by markus-wa** [comment]
Hey, sorry but I don't even know which of the three demos I'm supposed to look at, at which time it happens (since i'll need to open the demo in CS:GO to see what the game says), which version you used (placeholder text) or any debug output.

I'd appreciate it if the issues would be more detailed or if you prefer short questions it would be easier to do it via Gitter where we can get immediate feedback from each other: https://gitter.im/csgodemos/demoinfo-lib

thanks 🙂

**Comment by quancore** [comment]
Thanks for your clarification. It is the same demofile with previous issue. I have changed output with the one also includes ticks.
For generation of output: 
see: https://github.com/markus-wa/demoinfocs-golang/issues/83#issuecomment-454762603

**Comment by markus-wa** [comment]
Thanks!

Unfortunately this is the correct behavior, the score does get updated to 0:2 for 14 ticks (243075 - 243089).
Screenshot from the game: https://i.imgur.com/uLnhxaD.png

I'm not sure what to do here since `ScoreUpdated` was originally intended to circumvent some issues with `RoundEnd` (see #54 & #55).

@micvbang have you encountered something similar? do you have any suggestion here?

**Comment by quancore** [comment]
Any suggestion coming from @micvbang will be appreciated. And also could you check the match result as well because it gives the wrong score at the end:
https://ibb.co/SrK8qs3
which should be:
https://www.hltv.org/stats/matches/mapstatsid/79824/izako-boars-vs-gunrunners

**Comment by markus-wa** [comment]
Scores at the end of the demo are entierly unreliable, many plugins reset the score to 0-0 at the end and then start a new game.

If the recording isn't stopped the CTs will win every round which will lead to almost any score being possible at the end of a demo. In this case it was stopped after being reset to 0-0.

**Comment by markus-wa** [comment]
I doubt there is a bullet proof way. Technically a single demo file can contain two matches of different teams if the server starts recording at the beginning of one match and only ends after the second (though I haven't seen a professional match recorded like this so far).

**Comment by micvbang** [comment]
Yeah, definitely encountered something similar. As far as I can tell, `ScoreUpdated` tells you the score as it's displayed in-game, and should be trusted. The problem seems to be crappy (for our purposes anyway) plugins that mess with the game state. I've lost quite a bit of hair in the process of trying to figure this out :haircut_man: 

There isn't a simple way to find the final score - as @markus-wa says, we can't even know if a single demo contains only 1 match.

**Comment by markus-wa** [comment]
Closing, feel free to reopen if you feel like there's more to be discussed
