### ISSUE TITLE
Warm up event ignore

### ISSUE THREAD

**Issue by quancore** [markus-wa/demoinfocs-golang#92]
**Higher goal**
An option for a parser to event trigger during warm-up sessions.

**Describe the solution you'd like**
Probably a bool var. to indicate whether warm-up will be ignored or not in parser conf.

**Comment by markus-wa** [comment]
The goal of the parser is to avoid any kind of fuzzy logic in general. There are some compromises in some places but this isn't something I'd like to have in the core lib.

The main reason is that csgo demos are too unreliable to do it with 100% certainty.

Also 'higher goal' as it is now is too specific. A good example would be "i don't want warmup data to be considered for my statistical analysis". This would allow me to suggest other solutions to the problem.

**Comment by quancore** [comment]
At least on round start or round end, it would be wonderful to see whether it is a warm up round if possible.

**Comment by micvbang** [comment]
I thoroughly agree with @markus-wa here. In my opinion, the best we can aim for in this library is that it only outputs events that with certainty were part of the demo, with no fuzzy logic. As soon as we add fuzzy logic in one place, it's very difficult to argue that it shouldn't be added in another. And then the library quickly moves towards supporting some of the crazy formats that e.g. ESL/ESEA output.

So far, I've not been able to come up with a way to accurately determine (i.e. without fuzzy logic) whether a round is a warmup round or not. If it's possible, it would be wonderful to include in the parser. 
What makes this problem hard is to solve is that we only need to find one demo that behaves differently, in order to discard a certain solution.

**Comment by markus-wa** [comment]
Closing for now, feel free to reopen if you feel like there's more to be discussed
